import { z } from "zod";

// ── Source Agency enum ─────────────────────────────────────────────────────────
export const SourceAgencyEnum = z.enum([
    "CDSCO",
    "USFDA",
    "EU_MDR",
    "MDSAP",
    "OTHER",
]);
export type SourceAgency = z.infer<typeof SourceAgencyEnum>;

// ── Update Type enum ───────────────────────────────────────────────────────────
export const UpdateTypeEnum = z.enum([
    "Guidance",
    "Recall",
    "Final Rule",
    "Warning Letter",
    "Draft Guidance",
    "Safety Alert",
    "Notification",
    "Standard Update",
    "Other",
]);
export type UpdateType = z.infer<typeof UpdateTypeEnum>;

// ── Impact Level enum ──────────────────────────────────────────────────────────
export const ImpactEnum = z.enum(["High", "Medium", "Low"]);
export type Impact = z.infer<typeof ImpactEnum>;

// ── AI Output Schema (what the LLM returns per item) ───────────────────────────
// source_url and published_date are NOT generated by AI — they are merged after.
export const AIItemSchema = z.object({
    is_relevant: z.boolean(),
    source_agency: SourceAgencyEnum,
    update_type: UpdateTypeEnum,
    impact: ImpactEnum,
    jurisdiction: z.string(),
    device_types: z.array(z.string()),
    summary: z.string(),
    effective_date: z.string(),
    deadline: z.string(),
    action_required: z.string(),
});
export type AIItem = z.infer<typeof AIItemSchema>;

// ── Full Regulatory Item (AI output + backend-merged fields) ───────────────────
export const RegulatoryItemSchema = AIItemSchema.extend({
    title: z.string(),
    source_url: z.string(),
    published_date: z.string(),
}).omit({ is_relevant: true }); // is_relevant is used for filtering, not passed to UI

export type RegulatoryItem = z.infer<typeof RegulatoryItemSchema>;
