const fs = require('fs');
const path = require('path');

const codes = [
  { code: "+1", name: "US", country: "United States" },
  { code: "+1", name: "CA", country: "Canada" },
  { code: "+7", name: "RU", country: "Russia" },
  { code: "+7", name: "KZ", country: "Kazakhstan" },
  { code: "+20", name: "EG", country: "Egypt" },
  { code: "+27", name: "ZA", country: "South Africa" },
  { code: "+30", name: "GR", country: "Greece" },
  { code: "+31", name: "NL", country: "Netherlands" },
  { code: "+32", name: "BE", country: "Belgium" },
  { code: "+33", name: "FR", country: "France" },
  { code: "+34", name: "ES", country: "Spain" },
  { code: "+36", name: "HU", country: "Hungary" },
  { code: "+39", name: "IT", country: "Italy" },
  { code: "+40", name: "RO", country: "Romania" },
  { code: "+41", name: "CH", country: "Switzerland" },
  { code: "+43", name: "AT", country: "Austria" },
  { code: "+44", name: "GB", country: "United Kingdom" },
  { code: "+45", name: "DK", country: "Denmark" },
  { code: "+46", name: "SE", country: "Sweden" },
  { code: "+47", name: "NO", country: "Norway" },
  { code: "+48", name: "PL", country: "Poland" },
  { code: "+49", name: "DE", country: "Germany" },
  { code: "+51", name: "PE", country: "Peru" },
  { code: "+52", name: "MX", country: "Mexico" },
  { code: "+53", name: "CU", country: "Cuba" },
  { code: "+54", name: "AR", country: "Argentina" },
  { code: "+55", name: "BR", country: "Brazil" },
  { code: "+56", name: "CL", country: "Chile" },
  { code: "+57", name: "CO", country: "Colombia" },
  { code: "+58", name: "VE", country: "Venezuela" },
  { code: "+60", name: "MY", country: "Malaysia" },
  { code: "+61", name: "AU", country: "Australia" },
  { code: "+62", name: "ID", country: "Indonesia" },
  { code: "+63", name: "PH", country: "Philippines" },
  { code: "+64", name: "NZ", country: "New Zealand" },
  { code: "+65", name: "SG", country: "Singapore" },
  { code: "+66", name: "TH", country: "Thailand" },
  { code: "+81", name: "JP", country: "Japan" },
  { code: "+82", name: "KR", country: "South Korea" },
  { code: "+84", name: "VN", country: "Vietnam" },
  { code: "+86", name: "CN", country: "China" },
  { code: "+90", name: "TR", country: "Turkey" },
  { code: "+91", name: "IN", country: "India" },
  { code: "+92", name: "PK", country: "Pakistan" },
  { code: "+93", name: "AF", country: "Afghanistan" },
  { code: "+94", name: "LK", country: "Sri Lanka" },
  { code: "+95", name: "MM", country: "Myanmar" },
  { code: "+98", name: "IR", country: "Iran" },
  { code: "+212", name: "MA", country: "Morocco" },
  { code: "+213", name: "DZ", country: "Algeria" },
  { code: "+216", name: "TN", country: "Tunisia" },
  { code: "+218", name: "LY", country: "Libya" },
  { code: "+220", name: "GM", country: "Gambia" },
  { code: "+221", name: "SN", country: "Senegal" },
  { code: "+234", name: "NG", country: "Nigeria" },
  { code: "+254", name: "KE", country: "Kenya" },
  { code: "+255", name: "TZ", country: "Tanzania" },
  { code: "+256", name: "UG", country: "Uganda" },
  { code: "+260", name: "ZM", country: "Zambia" },
  { code: "+263", name: "ZW", country: "Zimbabwe" },
  { code: "+351", name: "PT", country: "Portugal" },
  { code: "+353", name: "IE", country: "Ireland" },
  { code: "+355", name: "AL", country: "Albania" },
  { code: "+358", name: "FI", country: "Finland" },
  { code: "+359", name: "BG", country: "Bulgaria" },
  { code: "+370", name: "LT", country: "Lithuania" },
  { code: "+371", name: "LV", country: "Latvia" },
  { code: "+372", name: "EE", country: "Estonia" },
  { code: "+373", name: "MD", country: "Moldova" },
  { code: "+374", name: "AM", country: "Armenia" },
  { code: "+375", name: "BY", country: "Belarus" },
  { code: "+376", name: "AD", country: "Andorra" },
  { code: "+380", name: "UA", country: "Ukraine" },
  { code: "+381", name: "RS", country: "Serbia" },
  { code: "+382", name: "ME", country: "Montenegro" },
  { code: "+385", name: "HR", country: "Croatia" },
  { code: "+386", name: "SI", country: "Slovenia" },
  { code: "+387", name: "BA", country: "Bosnia and Herzegovina" },
  { code: "+389", name: "MK", country: "North Macedonia" },
  { code: "+420", name: "CZ", country: "Czech Republic" },
  { code: "+421", name: "SK", country: "Slovakia" },
  { code: "+501", name: "BZ", country: "Belize" },
  { code: "+502", name: "GT", country: "Guatemala" },
  { code: "+503", name: "SV", country: "El Salvador" },
  { code: "+504", name: "HN", country: "Honduras" },
  { code: "+505", name: "NI", country: "Nicaragua" },
  { code: "+506", name: "CR", country: "Costa Rica" },
  { code: "+507", name: "PA", country: "Panama" },
  { code: "+591", name: "BO", country: "Bolivia" },
  { code: "+593", name: "EC", country: "Ecuador" },
  { code: "+595", name: "PY", country: "Paraguay" },
  { code: "+598", name: "UY", country: "Uruguay" },
  { code: "+852", name: "HK", country: "Hong Kong" },
  { code: "+853", name: "MO", country: "Macau" },
  { code: "+880", name: "BD", country: "Bangladesh" },
  { code: "+886", name: "TW", country: "Taiwan" },
  { code: "+960", name: "MV", country: "Maldives" },
  { code: "+961", name: "LB", country: "Lebanon" },
  { code: "+962", name: "JO", country: "Jordan" },
  { code: "+963", name: "SY", country: "Syria" },
  { code: "+964", name: "IQ", country: "Iraq" },
  { code: "+965", name: "KW", country: "Kuwait" },
  { code: "+966", name: "SA", country: "Saudi Arabia" },
  { code: "+967", name: "YE", country: "Yemen" },
  { code: "+968", name: "OM", country: "Oman" },
  { code: "+971", name: "AE", country: "United Arab Emirates" },
  { code: "+972", name: "IL", country: "Israel" },
  { code: "+973", name: "BH", country: "Bahrain" },
  { code: "+974", name: "QA", country: "Qatar" },
  { code: "+975", name: "BT", country: "Bhutan" },
  { code: "+976", name: "MN", country: "Mongolia" },
  { code: "+977", name: "NP", country: "Nepal" },
  { code: "+992", name: "TJ", country: "Tajikistan" },
  { code: "+993", name: "TM", country: "Turkmenistan" },
  { code: "+994", name: "AZ", country: "Azerbaijan" },
  { code: "+995", name: "GE", country: "Georgia" },
  { code: "+996", name: "KG", country: "Kyrgyzstan" },
  { code: "+998", name: "UZ", country: "Uzbekistan" }
].sort((a, b) => a.country.localeCompare(b.country));

function getFlagEmoji(countryCode) {
  const codePoints = countryCode
    .toUpperCase()
    .split('')
    .map(char =>  127397 + char.charCodeAt());
  return String.fromCodePoint(...codePoints);
}

const withFlags = codes.map(c => ({
  ...c,
  flag: getFlagEmoji(c.name)
}));

let content = "export const countryCodes = " + JSON.stringify(withFlags, null, 2) + ";\n";
fs.writeFileSync(path.join(__dirname, 'src', 'lib', 'countryCodes.ts'), content);
console.log('Done');
