/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegulatoryUpdatesRouteImport } from './routes/regulatory-updates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatoryUpdatesRoute = RegulatoryUpdatesRouteImport.update({
  id: '/regulatory-updates',
  path: '/regulatory-updates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/regulatory-updates': typeof RegulatoryUpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/regulatory-updates': typeof RegulatoryUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/regulatory-updates': typeof RegulatoryUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/regulatory-updates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/regulatory-updates'
  id: '__root__' | '/' | '/regulatory-updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegulatoryUpdatesRoute: typeof RegulatoryUpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulatory-updates': {
      id: '/regulatory-updates'
      path: '/regulatory-updates'
      fullPath: '/regulatory-updates'
      preLoaderRoute: typeof RegulatoryUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegulatoryUpdatesRoute: RegulatoryUpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
