// AUTO-GENERATED by TanStack Router — run `npm run dev` to regenerate.
// This file is committed as a stub so TypeScript resolves the import
// before the dev server generates the real version.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as RegulatoryUpdatesRoute } from "./routes/regulatory-updates";
import {
    createRootRoute,
    createRoute,
    createRouter,
} from "@tanstack/react-router";

const routeTree = rootRoute.addChildren([
    IndexRoute,
    RegulatoryUpdatesRoute,
]);

export { routeTree };
