/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutcopyRouteImport } from './routes/about copy'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesAustraliaTgaRouteImport } from './routes/case-studies.australia-tga'
import { Route as CaseStudiesEuMdrRemediationRouteImport } from './routes/case-studies.eu-mdr-remediation'
import { Route as CaseStudiesFdaBiocompatibilityRouteImport } from './routes/case-studies.fda-biocompatibility'
import { Route as CaseStudiesFdaSimulatedUseRouteImport } from './routes/case-studies.fda-simulated-use'
import { Route as CaseStudiesTestSmarterRouteImport } from './routes/case-studies.test-smarter'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesCosmeticsRouteImport } from './routes/industries.cosmetics'
import { Route as IndustriesIvdRouteImport } from './routes/industries.ivd'
import { Route as IndustriesMedicalDevicesRouteImport } from './routes/industries.medical-devices'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsEuMdr2026RouteImport } from './routes/insights.eu-mdr-2026'
import { Route as InsightsFdaInspections2026RouteImport } from './routes/insights.fda-inspections-2026'
import { Route as InsightsFdaQmsr2026RouteImport } from './routes/insights.fda-qmsr-2026'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAustraliaRouteImport } from './routes/services.australia'
import { Route as ServicesBrazilRouteImport } from './routes/services.brazil'
import { Route as ServicesCanadaRouteImport } from './routes/services.canada'
import { Route as ServicesEuRouteImport } from './routes/services.eu'
import { Route as ServicesIndiaRouteImport } from './routes/services.india'
import { Route as ServicesIso13485RouteImport } from './routes/services.iso-13485'
import { Route as ServicesMdsapRouteImport } from './routes/services.mdsap'
import { Route as ServicesRegulatoryAffairsRouteImport } from './routes/services.regulatory-affairs'
import { Route as ServicesUaeRouteImport } from './routes/services.uae'
import { Route as ServicesUkRouteImport } from './routes/services.uk'
import { Route as ServicesUsaRouteImport } from './routes/services.usa'
import { Route as ServicesIndiaIndexRouteImport } from './routes/services.india.index'
import { Route as ServicesIndiaClassAImportRouteImport } from './routes/services.india.class-a-import'
import { Route as ServicesIndiaFreeSaleRouteImport } from './routes/services.india.free-sale'
import { Route as ServicesIndiaInvestigationalDevicesRouteImport } from './routes/services.india.investigational-devices'
import { Route as ServicesIndiaIvdClinicalPerformanceRouteImport } from './routes/services.india.ivd-clinical-performance'
import { Route as ServicesIndiaIvdTestingRouteImport } from './routes/services.india.ivd-testing'
import { Route as ServicesIndiaLoanClassABRouteImport } from './routes/services.india.loan-class-a-b'
import { Route as ServicesIndiaLoanClassCDRouteImport } from './routes/services.india.loan-class-c-d'
import { Route as ServicesIndiaMarketStandingRouteImport } from './routes/services.india.market-standing'
import { Route as ServicesIndiaMd42RouteImport } from './routes/services.india.md-42'
import { Route as ServicesIndiaMfgClassABRouteImport } from './routes/services.india.mfg-class-a-b'
import { Route as ServicesIndiaMfgClassAGsrRouteImport } from './routes/services.india.mfg-class-a-gsr'
import { Route as ServicesIndiaMfgClassCDRouteImport } from './routes/services.india.mfg-class-c-d'
import { Route as ServicesIndiaNeutralCodeRouteImport } from './routes/services.india.neutral-code'
import { Route as ServicesIndiaNonConvictionRouteImport } from './routes/services.india.non-conviction'
import { Route as ServicesIndiaNovelIvdsRouteImport } from './routes/services.india.novel-ivds'
import { Route as ServicesIndiaPersonalUseRouteImport } from './routes/services.india.personal-use'
import { Route as ServicesIndiaPredicateDevicesRouteImport } from './routes/services.india.predicate-devices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutcopyRoute = AboutcopyRouteImport.update({
  id: '/about copy',
  path: '/about copy',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesAustraliaTgaRoute = CaseStudiesAustraliaTgaRouteImport.update({
  id: '/australia-tga',
  path: '/australia-tga',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesEuMdrRemediationRoute =
  CaseStudiesEuMdrRemediationRouteImport.update({
    id: '/eu-mdr-remediation',
    path: '/eu-mdr-remediation',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesFdaBiocompatibilityRoute =
  CaseStudiesFdaBiocompatibilityRouteImport.update({
    id: '/fda-biocompatibility',
    path: '/fda-biocompatibility',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesFdaSimulatedUseRoute =
  CaseStudiesFdaSimulatedUseRouteImport.update({
    id: '/fda-simulated-use',
    path: '/fda-simulated-use',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesTestSmarterRoute = CaseStudiesTestSmarterRouteImport.update({
  id: '/test-smarter',
  path: '/test-smarter',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesCosmeticsRoute = IndustriesCosmeticsRouteImport.update({
  id: '/industries/cosmetics',
  path: '/industries/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIvdRoute = IndustriesIvdRouteImport.update({
  id: '/industries/ivd',
  path: '/industries/ivd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesMedicalDevicesRoute =
  IndustriesMedicalDevicesRouteImport.update({
    id: '/industries/medical-devices',
    path: '/industries/medical-devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsEuMdr2026Route = InsightsEuMdr2026RouteImport.update({
  id: '/insights/eu-mdr-2026',
  path: '/insights/eu-mdr-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsFdaInspections2026Route =
  InsightsFdaInspections2026RouteImport.update({
    id: '/insights/fda-inspections-2026',
    path: '/insights/fda-inspections-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsFdaQmsr2026Route = InsightsFdaQmsr2026RouteImport.update({
  id: '/insights/fda-qmsr-2026',
  path: '/insights/fda-qmsr-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAustraliaRoute = ServicesAustraliaRouteImport.update({
  id: '/services/australia',
  path: '/services/australia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrazilRoute = ServicesBrazilRouteImport.update({
  id: '/services/brazil',
  path: '/services/brazil',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCanadaRoute = ServicesCanadaRouteImport.update({
  id: '/services/canada',
  path: '/services/canada',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEuRoute = ServicesEuRouteImport.update({
  id: '/services/eu',
  path: '/services/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndiaRoute = ServicesIndiaRouteImport.update({
  id: '/services/india',
  path: '/services/india',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIso13485Route = ServicesIso13485RouteImport.update({
  id: '/services/iso-13485',
  path: '/services/iso-13485',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMdsapRoute = ServicesMdsapRouteImport.update({
  id: '/services/mdsap',
  path: '/services/mdsap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRegulatoryAffairsRoute =
  ServicesRegulatoryAffairsRouteImport.update({
    id: '/services/regulatory-affairs',
    path: '/services/regulatory-affairs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUaeRoute = ServicesUaeRouteImport.update({
  id: '/services/uae',
  path: '/services/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUkRoute = ServicesUkRouteImport.update({
  id: '/services/uk',
  path: '/services/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUsaRoute = ServicesUsaRouteImport.update({
  id: '/services/usa',
  path: '/services/usa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndiaIndexRoute = ServicesIndiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaClassAImportRoute =
  ServicesIndiaClassAImportRouteImport.update({
    id: '/class-a-import',
    path: '/class-a-import',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaFreeSaleRoute = ServicesIndiaFreeSaleRouteImport.update({
  id: '/free-sale',
  path: '/free-sale',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaInvestigationalDevicesRoute =
  ServicesIndiaInvestigationalDevicesRouteImport.update({
    id: '/investigational-devices',
    path: '/investigational-devices',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaIvdClinicalPerformanceRoute =
  ServicesIndiaIvdClinicalPerformanceRouteImport.update({
    id: '/ivd-clinical-performance',
    path: '/ivd-clinical-performance',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaIvdTestingRoute = ServicesIndiaIvdTestingRouteImport.update({
  id: '/ivd-testing',
  path: '/ivd-testing',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaLoanClassABRoute =
  ServicesIndiaLoanClassABRouteImport.update({
    id: '/loan-class-a-b',
    path: '/loan-class-a-b',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaLoanClassCDRoute =
  ServicesIndiaLoanClassCDRouteImport.update({
    id: '/loan-class-c-d',
    path: '/loan-class-c-d',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaMarketStandingRoute =
  ServicesIndiaMarketStandingRouteImport.update({
    id: '/market-standing',
    path: '/market-standing',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaMd42Route = ServicesIndiaMd42RouteImport.update({
  id: '/md-42',
  path: '/md-42',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaMfgClassABRoute = ServicesIndiaMfgClassABRouteImport.update({
  id: '/mfg-class-a-b',
  path: '/mfg-class-a-b',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaMfgClassAGsrRoute =
  ServicesIndiaMfgClassAGsrRouteImport.update({
    id: '/mfg-class-a-gsr',
    path: '/mfg-class-a-gsr',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaMfgClassCDRoute = ServicesIndiaMfgClassCDRouteImport.update({
  id: '/mfg-class-c-d',
  path: '/mfg-class-c-d',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaNeutralCodeRoute =
  ServicesIndiaNeutralCodeRouteImport.update({
    id: '/neutral-code',
    path: '/neutral-code',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaNonConvictionRoute =
  ServicesIndiaNonConvictionRouteImport.update({
    id: '/non-conviction',
    path: '/non-conviction',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaNovelIvdsRoute = ServicesIndiaNovelIvdsRouteImport.update({
  id: '/novel-ivds',
  path: '/novel-ivds',
  getParentRoute: () => ServicesIndiaRoute,
} as any)
const ServicesIndiaPersonalUseRoute =
  ServicesIndiaPersonalUseRouteImport.update({
    id: '/personal-use',
    path: '/personal-use',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)
const ServicesIndiaPredicateDevicesRoute =
  ServicesIndiaPredicateDevicesRouteImport.update({
    id: '/predicate-devices',
    path: '/predicate-devices',
    getParentRoute: () => ServicesIndiaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about copy': typeof AboutcopyRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/india': typeof ServicesIndiaRouteWithChildren
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/india/class-a-import': typeof ServicesIndiaClassAImportRoute
  '/services/india/free-sale': typeof ServicesIndiaFreeSaleRoute
  '/services/india/investigational-devices': typeof ServicesIndiaInvestigationalDevicesRoute
  '/services/india/ivd-clinical-performance': typeof ServicesIndiaIvdClinicalPerformanceRoute
  '/services/india/ivd-testing': typeof ServicesIndiaIvdTestingRoute
  '/services/india/loan-class-a-b': typeof ServicesIndiaLoanClassABRoute
  '/services/india/loan-class-c-d': typeof ServicesIndiaLoanClassCDRoute
  '/services/india/market-standing': typeof ServicesIndiaMarketStandingRoute
  '/services/india/md-42': typeof ServicesIndiaMd42Route
  '/services/india/mfg-class-a-b': typeof ServicesIndiaMfgClassABRoute
  '/services/india/mfg-class-a-gsr': typeof ServicesIndiaMfgClassAGsrRoute
  '/services/india/mfg-class-c-d': typeof ServicesIndiaMfgClassCDRoute
  '/services/india/neutral-code': typeof ServicesIndiaNeutralCodeRoute
  '/services/india/non-conviction': typeof ServicesIndiaNonConvictionRoute
  '/services/india/novel-ivds': typeof ServicesIndiaNovelIvdsRoute
  '/services/india/personal-use': typeof ServicesIndiaPersonalUseRoute
  '/services/india/predicate-devices': typeof ServicesIndiaPredicateDevicesRoute
  '/services/india/': typeof ServicesIndiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about copy': typeof AboutcopyRoute
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/india/class-a-import': typeof ServicesIndiaClassAImportRoute
  '/services/india/free-sale': typeof ServicesIndiaFreeSaleRoute
  '/services/india/investigational-devices': typeof ServicesIndiaInvestigationalDevicesRoute
  '/services/india/ivd-clinical-performance': typeof ServicesIndiaIvdClinicalPerformanceRoute
  '/services/india/ivd-testing': typeof ServicesIndiaIvdTestingRoute
  '/services/india/loan-class-a-b': typeof ServicesIndiaLoanClassABRoute
  '/services/india/loan-class-c-d': typeof ServicesIndiaLoanClassCDRoute
  '/services/india/market-standing': typeof ServicesIndiaMarketStandingRoute
  '/services/india/md-42': typeof ServicesIndiaMd42Route
  '/services/india/mfg-class-a-b': typeof ServicesIndiaMfgClassABRoute
  '/services/india/mfg-class-a-gsr': typeof ServicesIndiaMfgClassAGsrRoute
  '/services/india/mfg-class-c-d': typeof ServicesIndiaMfgClassCDRoute
  '/services/india/neutral-code': typeof ServicesIndiaNeutralCodeRoute
  '/services/india/non-conviction': typeof ServicesIndiaNonConvictionRoute
  '/services/india/novel-ivds': typeof ServicesIndiaNovelIvdsRoute
  '/services/india/personal-use': typeof ServicesIndiaPersonalUseRoute
  '/services/india/predicate-devices': typeof ServicesIndiaPredicateDevicesRoute
  '/services/india': typeof ServicesIndiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about copy': typeof AboutcopyRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/india': typeof ServicesIndiaRouteWithChildren
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/india/class-a-import': typeof ServicesIndiaClassAImportRoute
  '/services/india/free-sale': typeof ServicesIndiaFreeSaleRoute
  '/services/india/investigational-devices': typeof ServicesIndiaInvestigationalDevicesRoute
  '/services/india/ivd-clinical-performance': typeof ServicesIndiaIvdClinicalPerformanceRoute
  '/services/india/ivd-testing': typeof ServicesIndiaIvdTestingRoute
  '/services/india/loan-class-a-b': typeof ServicesIndiaLoanClassABRoute
  '/services/india/loan-class-c-d': typeof ServicesIndiaLoanClassCDRoute
  '/services/india/market-standing': typeof ServicesIndiaMarketStandingRoute
  '/services/india/md-42': typeof ServicesIndiaMd42Route
  '/services/india/mfg-class-a-b': typeof ServicesIndiaMfgClassABRoute
  '/services/india/mfg-class-a-gsr': typeof ServicesIndiaMfgClassAGsrRoute
  '/services/india/mfg-class-c-d': typeof ServicesIndiaMfgClassCDRoute
  '/services/india/neutral-code': typeof ServicesIndiaNeutralCodeRoute
  '/services/india/non-conviction': typeof ServicesIndiaNonConvictionRoute
  '/services/india/novel-ivds': typeof ServicesIndiaNovelIvdsRoute
  '/services/india/personal-use': typeof ServicesIndiaPersonalUseRoute
  '/services/india/predicate-devices': typeof ServicesIndiaPredicateDevicesRoute
  '/services/india/': typeof ServicesIndiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about copy'
    | '/case-studies'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/india'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/markets/'
    | '/services/'
    | '/services/india/class-a-import'
    | '/services/india/free-sale'
    | '/services/india/investigational-devices'
    | '/services/india/ivd-clinical-performance'
    | '/services/india/ivd-testing'
    | '/services/india/loan-class-a-b'
    | '/services/india/loan-class-c-d'
    | '/services/india/market-standing'
    | '/services/india/md-42'
    | '/services/india/mfg-class-a-b'
    | '/services/india/mfg-class-a-gsr'
    | '/services/india/mfg-class-c-d'
    | '/services/india/neutral-code'
    | '/services/india/non-conviction'
    | '/services/india/novel-ivds'
    | '/services/india/personal-use'
    | '/services/india/predicate-devices'
    | '/services/india/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about copy'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies'
    | '/industries'
    | '/insights'
    | '/markets'
    | '/services'
    | '/services/india/class-a-import'
    | '/services/india/free-sale'
    | '/services/india/investigational-devices'
    | '/services/india/ivd-clinical-performance'
    | '/services/india/ivd-testing'
    | '/services/india/loan-class-a-b'
    | '/services/india/loan-class-c-d'
    | '/services/india/market-standing'
    | '/services/india/md-42'
    | '/services/india/mfg-class-a-b'
    | '/services/india/mfg-class-a-gsr'
    | '/services/india/mfg-class-c-d'
    | '/services/india/neutral-code'
    | '/services/india/non-conviction'
    | '/services/india/novel-ivds'
    | '/services/india/personal-use'
    | '/services/india/predicate-devices'
    | '/services/india'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about copy'
    | '/case-studies'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/india'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/markets/'
    | '/services/'
    | '/services/india/class-a-import'
    | '/services/india/free-sale'
    | '/services/india/investigational-devices'
    | '/services/india/ivd-clinical-performance'
    | '/services/india/ivd-testing'
    | '/services/india/loan-class-a-b'
    | '/services/india/loan-class-c-d'
    | '/services/india/market-standing'
    | '/services/india/md-42'
    | '/services/india/mfg-class-a-b'
    | '/services/india/mfg-class-a-gsr'
    | '/services/india/mfg-class-c-d'
    | '/services/india/neutral-code'
    | '/services/india/non-conviction'
    | '/services/india/novel-ivds'
    | '/services/india/personal-use'
    | '/services/india/predicate-devices'
    | '/services/india/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutcopyRoute: typeof AboutcopyRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesCosmeticsRoute: typeof IndustriesCosmeticsRoute
  IndustriesIvdRoute: typeof IndustriesIvdRoute
  IndustriesMedicalDevicesRoute: typeof IndustriesMedicalDevicesRoute
  InsightsEuMdr2026Route: typeof InsightsEuMdr2026Route
  InsightsFdaInspections2026Route: typeof InsightsFdaInspections2026Route
  InsightsFdaQmsr2026Route: typeof InsightsFdaQmsr2026Route
  ServicesAustraliaRoute: typeof ServicesAustraliaRoute
  ServicesBrazilRoute: typeof ServicesBrazilRoute
  ServicesCanadaRoute: typeof ServicesCanadaRoute
  ServicesEuRoute: typeof ServicesEuRoute
  ServicesIndiaRoute: typeof ServicesIndiaRouteWithChildren
  ServicesIso13485Route: typeof ServicesIso13485Route
  ServicesMdsapRoute: typeof ServicesMdsapRoute
  ServicesRegulatoryAffairsRoute: typeof ServicesRegulatoryAffairsRoute
  ServicesUaeRoute: typeof ServicesUaeRoute
  ServicesUkRoute: typeof ServicesUkRoute
  ServicesUsaRoute: typeof ServicesUsaRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about copy': {
      id: '/about copy'
      path: '/about copy'
      fullPath: '/about copy'
      preLoaderRoute: typeof AboutcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/australia-tga': {
      id: '/case-studies/australia-tga'
      path: '/australia-tga'
      fullPath: '/case-studies/australia-tga'
      preLoaderRoute: typeof CaseStudiesAustraliaTgaRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/eu-mdr-remediation': {
      id: '/case-studies/eu-mdr-remediation'
      path: '/eu-mdr-remediation'
      fullPath: '/case-studies/eu-mdr-remediation'
      preLoaderRoute: typeof CaseStudiesEuMdrRemediationRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/fda-biocompatibility': {
      id: '/case-studies/fda-biocompatibility'
      path: '/fda-biocompatibility'
      fullPath: '/case-studies/fda-biocompatibility'
      preLoaderRoute: typeof CaseStudiesFdaBiocompatibilityRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/fda-simulated-use': {
      id: '/case-studies/fda-simulated-use'
      path: '/fda-simulated-use'
      fullPath: '/case-studies/fda-simulated-use'
      preLoaderRoute: typeof CaseStudiesFdaSimulatedUseRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/test-smarter': {
      id: '/case-studies/test-smarter'
      path: '/test-smarter'
      fullPath: '/case-studies/test-smarter'
      preLoaderRoute: typeof CaseStudiesTestSmarterRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/cosmetics': {
      id: '/industries/cosmetics'
      path: '/industries/cosmetics'
      fullPath: '/industries/cosmetics'
      preLoaderRoute: typeof IndustriesCosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/ivd': {
      id: '/industries/ivd'
      path: '/industries/ivd'
      fullPath: '/industries/ivd'
      preLoaderRoute: typeof IndustriesIvdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/medical-devices': {
      id: '/industries/medical-devices'
      path: '/industries/medical-devices'
      fullPath: '/industries/medical-devices'
      preLoaderRoute: typeof IndustriesMedicalDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/eu-mdr-2026': {
      id: '/insights/eu-mdr-2026'
      path: '/insights/eu-mdr-2026'
      fullPath: '/insights/eu-mdr-2026'
      preLoaderRoute: typeof InsightsEuMdr2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/fda-inspections-2026': {
      id: '/insights/fda-inspections-2026'
      path: '/insights/fda-inspections-2026'
      fullPath: '/insights/fda-inspections-2026'
      preLoaderRoute: typeof InsightsFdaInspections2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/fda-qmsr-2026': {
      id: '/insights/fda-qmsr-2026'
      path: '/insights/fda-qmsr-2026'
      fullPath: '/insights/fda-qmsr-2026'
      preLoaderRoute: typeof InsightsFdaQmsr2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/australia': {
      id: '/services/australia'
      path: '/services/australia'
      fullPath: '/services/australia'
      preLoaderRoute: typeof ServicesAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brazil': {
      id: '/services/brazil'
      path: '/services/brazil'
      fullPath: '/services/brazil'
      preLoaderRoute: typeof ServicesBrazilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/canada': {
      id: '/services/canada'
      path: '/services/canada'
      fullPath: '/services/canada'
      preLoaderRoute: typeof ServicesCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/eu': {
      id: '/services/eu'
      path: '/services/eu'
      fullPath: '/services/eu'
      preLoaderRoute: typeof ServicesEuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/india': {
      id: '/services/india'
      path: '/services/india'
      fullPath: '/services/india'
      preLoaderRoute: typeof ServicesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/iso-13485': {
      id: '/services/iso-13485'
      path: '/services/iso-13485'
      fullPath: '/services/iso-13485'
      preLoaderRoute: typeof ServicesIso13485RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mdsap': {
      id: '/services/mdsap'
      path: '/services/mdsap'
      fullPath: '/services/mdsap'
      preLoaderRoute: typeof ServicesMdsapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/regulatory-affairs': {
      id: '/services/regulatory-affairs'
      path: '/services/regulatory-affairs'
      fullPath: '/services/regulatory-affairs'
      preLoaderRoute: typeof ServicesRegulatoryAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uae': {
      id: '/services/uae'
      path: '/services/uae'
      fullPath: '/services/uae'
      preLoaderRoute: typeof ServicesUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uk': {
      id: '/services/uk'
      path: '/services/uk'
      fullPath: '/services/uk'
      preLoaderRoute: typeof ServicesUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/usa': {
      id: '/services/usa'
      path: '/services/usa'
      fullPath: '/services/usa'
      preLoaderRoute: typeof ServicesUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/india/': {
      id: '/services/india/'
      path: '/'
      fullPath: '/services/india/'
      preLoaderRoute: typeof ServicesIndiaIndexRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/class-a-import': {
      id: '/services/india/class-a-import'
      path: '/class-a-import'
      fullPath: '/services/india/class-a-import'
      preLoaderRoute: typeof ServicesIndiaClassAImportRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/free-sale': {
      id: '/services/india/free-sale'
      path: '/free-sale'
      fullPath: '/services/india/free-sale'
      preLoaderRoute: typeof ServicesIndiaFreeSaleRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/investigational-devices': {
      id: '/services/india/investigational-devices'
      path: '/investigational-devices'
      fullPath: '/services/india/investigational-devices'
      preLoaderRoute: typeof ServicesIndiaInvestigationalDevicesRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/ivd-clinical-performance': {
      id: '/services/india/ivd-clinical-performance'
      path: '/ivd-clinical-performance'
      fullPath: '/services/india/ivd-clinical-performance'
      preLoaderRoute: typeof ServicesIndiaIvdClinicalPerformanceRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/ivd-testing': {
      id: '/services/india/ivd-testing'
      path: '/ivd-testing'
      fullPath: '/services/india/ivd-testing'
      preLoaderRoute: typeof ServicesIndiaIvdTestingRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/loan-class-a-b': {
      id: '/services/india/loan-class-a-b'
      path: '/loan-class-a-b'
      fullPath: '/services/india/loan-class-a-b'
      preLoaderRoute: typeof ServicesIndiaLoanClassABRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/loan-class-c-d': {
      id: '/services/india/loan-class-c-d'
      path: '/loan-class-c-d'
      fullPath: '/services/india/loan-class-c-d'
      preLoaderRoute: typeof ServicesIndiaLoanClassCDRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/market-standing': {
      id: '/services/india/market-standing'
      path: '/market-standing'
      fullPath: '/services/india/market-standing'
      preLoaderRoute: typeof ServicesIndiaMarketStandingRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/md-42': {
      id: '/services/india/md-42'
      path: '/md-42'
      fullPath: '/services/india/md-42'
      preLoaderRoute: typeof ServicesIndiaMd42RouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/mfg-class-a-b': {
      id: '/services/india/mfg-class-a-b'
      path: '/mfg-class-a-b'
      fullPath: '/services/india/mfg-class-a-b'
      preLoaderRoute: typeof ServicesIndiaMfgClassABRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/mfg-class-a-gsr': {
      id: '/services/india/mfg-class-a-gsr'
      path: '/mfg-class-a-gsr'
      fullPath: '/services/india/mfg-class-a-gsr'
      preLoaderRoute: typeof ServicesIndiaMfgClassAGsrRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/mfg-class-c-d': {
      id: '/services/india/mfg-class-c-d'
      path: '/mfg-class-c-d'
      fullPath: '/services/india/mfg-class-c-d'
      preLoaderRoute: typeof ServicesIndiaMfgClassCDRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/neutral-code': {
      id: '/services/india/neutral-code'
      path: '/neutral-code'
      fullPath: '/services/india/neutral-code'
      preLoaderRoute: typeof ServicesIndiaNeutralCodeRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/non-conviction': {
      id: '/services/india/non-conviction'
      path: '/non-conviction'
      fullPath: '/services/india/non-conviction'
      preLoaderRoute: typeof ServicesIndiaNonConvictionRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/novel-ivds': {
      id: '/services/india/novel-ivds'
      path: '/novel-ivds'
      fullPath: '/services/india/novel-ivds'
      preLoaderRoute: typeof ServicesIndiaNovelIvdsRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/personal-use': {
      id: '/services/india/personal-use'
      path: '/personal-use'
      fullPath: '/services/india/personal-use'
      preLoaderRoute: typeof ServicesIndiaPersonalUseRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
    '/services/india/predicate-devices': {
      id: '/services/india/predicate-devices'
      path: '/predicate-devices'
      fullPath: '/services/india/predicate-devices'
      preLoaderRoute: typeof ServicesIndiaPredicateDevicesRouteImport
      parentRoute: typeof ServicesIndiaRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesAustraliaTgaRoute: typeof CaseStudiesAustraliaTgaRoute
  CaseStudiesEuMdrRemediationRoute: typeof CaseStudiesEuMdrRemediationRoute
  CaseStudiesFdaBiocompatibilityRoute: typeof CaseStudiesFdaBiocompatibilityRoute
  CaseStudiesFdaSimulatedUseRoute: typeof CaseStudiesFdaSimulatedUseRoute
  CaseStudiesTestSmarterRoute: typeof CaseStudiesTestSmarterRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesAustraliaTgaRoute: CaseStudiesAustraliaTgaRoute,
  CaseStudiesEuMdrRemediationRoute: CaseStudiesEuMdrRemediationRoute,
  CaseStudiesFdaBiocompatibilityRoute: CaseStudiesFdaBiocompatibilityRoute,
  CaseStudiesFdaSimulatedUseRoute: CaseStudiesFdaSimulatedUseRoute,
  CaseStudiesTestSmarterRoute: CaseStudiesTestSmarterRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ServicesIndiaRouteChildren {
  ServicesIndiaClassAImportRoute: typeof ServicesIndiaClassAImportRoute
  ServicesIndiaFreeSaleRoute: typeof ServicesIndiaFreeSaleRoute
  ServicesIndiaInvestigationalDevicesRoute: typeof ServicesIndiaInvestigationalDevicesRoute
  ServicesIndiaIvdClinicalPerformanceRoute: typeof ServicesIndiaIvdClinicalPerformanceRoute
  ServicesIndiaIvdTestingRoute: typeof ServicesIndiaIvdTestingRoute
  ServicesIndiaLoanClassABRoute: typeof ServicesIndiaLoanClassABRoute
  ServicesIndiaLoanClassCDRoute: typeof ServicesIndiaLoanClassCDRoute
  ServicesIndiaMarketStandingRoute: typeof ServicesIndiaMarketStandingRoute
  ServicesIndiaMd42Route: typeof ServicesIndiaMd42Route
  ServicesIndiaMfgClassABRoute: typeof ServicesIndiaMfgClassABRoute
  ServicesIndiaMfgClassAGsrRoute: typeof ServicesIndiaMfgClassAGsrRoute
  ServicesIndiaMfgClassCDRoute: typeof ServicesIndiaMfgClassCDRoute
  ServicesIndiaNeutralCodeRoute: typeof ServicesIndiaNeutralCodeRoute
  ServicesIndiaNonConvictionRoute: typeof ServicesIndiaNonConvictionRoute
  ServicesIndiaNovelIvdsRoute: typeof ServicesIndiaNovelIvdsRoute
  ServicesIndiaPersonalUseRoute: typeof ServicesIndiaPersonalUseRoute
  ServicesIndiaPredicateDevicesRoute: typeof ServicesIndiaPredicateDevicesRoute
  ServicesIndiaIndexRoute: typeof ServicesIndiaIndexRoute
}

const ServicesIndiaRouteChildren: ServicesIndiaRouteChildren = {
  ServicesIndiaClassAImportRoute: ServicesIndiaClassAImportRoute,
  ServicesIndiaFreeSaleRoute: ServicesIndiaFreeSaleRoute,
  ServicesIndiaInvestigationalDevicesRoute:
    ServicesIndiaInvestigationalDevicesRoute,
  ServicesIndiaIvdClinicalPerformanceRoute:
    ServicesIndiaIvdClinicalPerformanceRoute,
  ServicesIndiaIvdTestingRoute: ServicesIndiaIvdTestingRoute,
  ServicesIndiaLoanClassABRoute: ServicesIndiaLoanClassABRoute,
  ServicesIndiaLoanClassCDRoute: ServicesIndiaLoanClassCDRoute,
  ServicesIndiaMarketStandingRoute: ServicesIndiaMarketStandingRoute,
  ServicesIndiaMd42Route: ServicesIndiaMd42Route,
  ServicesIndiaMfgClassABRoute: ServicesIndiaMfgClassABRoute,
  ServicesIndiaMfgClassAGsrRoute: ServicesIndiaMfgClassAGsrRoute,
  ServicesIndiaMfgClassCDRoute: ServicesIndiaMfgClassCDRoute,
  ServicesIndiaNeutralCodeRoute: ServicesIndiaNeutralCodeRoute,
  ServicesIndiaNonConvictionRoute: ServicesIndiaNonConvictionRoute,
  ServicesIndiaNovelIvdsRoute: ServicesIndiaNovelIvdsRoute,
  ServicesIndiaPersonalUseRoute: ServicesIndiaPersonalUseRoute,
  ServicesIndiaPredicateDevicesRoute: ServicesIndiaPredicateDevicesRoute,
  ServicesIndiaIndexRoute: ServicesIndiaIndexRoute,
}

const ServicesIndiaRouteWithChildren = ServicesIndiaRoute._addFileChildren(
  ServicesIndiaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutcopyRoute: AboutcopyRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesCosmeticsRoute: IndustriesCosmeticsRoute,
  IndustriesIvdRoute: IndustriesIvdRoute,
  IndustriesMedicalDevicesRoute: IndustriesMedicalDevicesRoute,
  InsightsEuMdr2026Route: InsightsEuMdr2026Route,
  InsightsFdaInspections2026Route: InsightsFdaInspections2026Route,
  InsightsFdaQmsr2026Route: InsightsFdaQmsr2026Route,
  ServicesAustraliaRoute: ServicesAustraliaRoute,
  ServicesBrazilRoute: ServicesBrazilRoute,
  ServicesCanadaRoute: ServicesCanadaRoute,
  ServicesEuRoute: ServicesEuRoute,
  ServicesIndiaRoute: ServicesIndiaRouteWithChildren,
  ServicesIso13485Route: ServicesIso13485Route,
  ServicesMdsapRoute: ServicesMdsapRoute,
  ServicesRegulatoryAffairsRoute: ServicesRegulatoryAffairsRoute,
  ServicesUaeRoute: ServicesUaeRoute,
  ServicesUkRoute: ServicesUkRoute,
  ServicesUsaRoute: ServicesUsaRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
