/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesAustraliaTgaRouteImport } from './routes/case-studies.australia-tga'
import { Route as CaseStudiesEuMdrRemediationRouteImport } from './routes/case-studies.eu-mdr-remediation'
import { Route as CaseStudiesFdaBiocompatibilityRouteImport } from './routes/case-studies.fda-biocompatibility'
import { Route as CaseStudiesFdaSimulatedUseRouteImport } from './routes/case-studies.fda-simulated-use'
import { Route as CaseStudiesTestSmarterRouteImport } from './routes/case-studies.test-smarter'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesCosmeticsRouteImport } from './routes/industries.cosmetics'
import { Route as IndustriesIvdRouteImport } from './routes/industries.ivd'
import { Route as IndustriesMedicalDevicesRouteImport } from './routes/industries.medical-devices'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsEuMdr2026RouteImport } from './routes/insights.eu-mdr-2026'
import { Route as InsightsFdaInspections2026RouteImport } from './routes/insights.fda-inspections-2026'
import { Route as InsightsFdaQmsr2026RouteImport } from './routes/insights.fda-qmsr-2026'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAustraliaRouteImport } from './routes/services.australia'
import { Route as ServicesBrazilRouteImport } from './routes/services.brazil'
import { Route as ServicesCanadaRouteImport } from './routes/services.canada'
import { Route as ServicesEuRouteImport } from './routes/services.eu'
import { Route as ServicesIndiaRouteImport } from './routes/services.india'
import { Route as ServicesIso13485RouteImport } from './routes/services.iso-13485'
import { Route as ServicesMdsapRouteImport } from './routes/services.mdsap'
import { Route as ServicesRegulatoryAffairsRouteImport } from './routes/services.regulatory-affairs'
import { Route as ServicesUaeRouteImport } from './routes/services.uae'
import { Route as ServicesUkRouteImport } from './routes/services.uk'
import { Route as ServicesUsaRouteImport } from './routes/services.usa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesAustraliaTgaRoute = CaseStudiesAustraliaTgaRouteImport.update({
  id: '/australia-tga',
  path: '/australia-tga',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesEuMdrRemediationRoute =
  CaseStudiesEuMdrRemediationRouteImport.update({
    id: '/eu-mdr-remediation',
    path: '/eu-mdr-remediation',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesFdaBiocompatibilityRoute =
  CaseStudiesFdaBiocompatibilityRouteImport.update({
    id: '/fda-biocompatibility',
    path: '/fda-biocompatibility',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesFdaSimulatedUseRoute =
  CaseStudiesFdaSimulatedUseRouteImport.update({
    id: '/fda-simulated-use',
    path: '/fda-simulated-use',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesTestSmarterRoute = CaseStudiesTestSmarterRouteImport.update({
  id: '/test-smarter',
  path: '/test-smarter',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesCosmeticsRoute = IndustriesCosmeticsRouteImport.update({
  id: '/industries/cosmetics',
  path: '/industries/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIvdRoute = IndustriesIvdRouteImport.update({
  id: '/industries/ivd',
  path: '/industries/ivd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesMedicalDevicesRoute =
  IndustriesMedicalDevicesRouteImport.update({
    id: '/industries/medical-devices',
    path: '/industries/medical-devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsEuMdr2026Route = InsightsEuMdr2026RouteImport.update({
  id: '/insights/eu-mdr-2026',
  path: '/insights/eu-mdr-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsFdaInspections2026Route =
  InsightsFdaInspections2026RouteImport.update({
    id: '/insights/fda-inspections-2026',
    path: '/insights/fda-inspections-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsFdaQmsr2026Route = InsightsFdaQmsr2026RouteImport.update({
  id: '/insights/fda-qmsr-2026',
  path: '/insights/fda-qmsr-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAustraliaRoute = ServicesAustraliaRouteImport.update({
  id: '/services/australia',
  path: '/services/australia',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrazilRoute = ServicesBrazilRouteImport.update({
  id: '/services/brazil',
  path: '/services/brazil',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCanadaRoute = ServicesCanadaRouteImport.update({
  id: '/services/canada',
  path: '/services/canada',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEuRoute = ServicesEuRouteImport.update({
  id: '/services/eu',
  path: '/services/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndiaRoute = ServicesIndiaRouteImport.update({
  id: '/services/india',
  path: '/services/india',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIso13485Route = ServicesIso13485RouteImport.update({
  id: '/services/iso-13485',
  path: '/services/iso-13485',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMdsapRoute = ServicesMdsapRouteImport.update({
  id: '/services/mdsap',
  path: '/services/mdsap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRegulatoryAffairsRoute =
  ServicesRegulatoryAffairsRouteImport.update({
    id: '/services/regulatory-affairs',
    path: '/services/regulatory-affairs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesUaeRoute = ServicesUaeRouteImport.update({
  id: '/services/uae',
  path: '/services/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUkRoute = ServicesUkRouteImport.update({
  id: '/services/uk',
  path: '/services/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUsaRoute = ServicesUsaRouteImport.update({
  id: '/services/usa',
  path: '/services/usa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/india': typeof ServicesIndiaRoute
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/india': typeof ServicesIndiaRoute
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/markets': typeof MarketsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/case-studies/australia-tga': typeof CaseStudiesAustraliaTgaRoute
  '/case-studies/eu-mdr-remediation': typeof CaseStudiesEuMdrRemediationRoute
  '/case-studies/fda-biocompatibility': typeof CaseStudiesFdaBiocompatibilityRoute
  '/case-studies/fda-simulated-use': typeof CaseStudiesFdaSimulatedUseRoute
  '/case-studies/test-smarter': typeof CaseStudiesTestSmarterRoute
  '/industries/cosmetics': typeof IndustriesCosmeticsRoute
  '/industries/ivd': typeof IndustriesIvdRoute
  '/industries/medical-devices': typeof IndustriesMedicalDevicesRoute
  '/insights/eu-mdr-2026': typeof InsightsEuMdr2026Route
  '/insights/fda-inspections-2026': typeof InsightsFdaInspections2026Route
  '/insights/fda-qmsr-2026': typeof InsightsFdaQmsr2026Route
  '/services/australia': typeof ServicesAustraliaRoute
  '/services/brazil': typeof ServicesBrazilRoute
  '/services/canada': typeof ServicesCanadaRoute
  '/services/eu': typeof ServicesEuRoute
  '/services/india': typeof ServicesIndiaRoute
  '/services/iso-13485': typeof ServicesIso13485Route
  '/services/mdsap': typeof ServicesMdsapRoute
  '/services/regulatory-affairs': typeof ServicesRegulatoryAffairsRoute
  '/services/uae': typeof ServicesUaeRoute
  '/services/uk': typeof ServicesUkRoute
  '/services/usa': typeof ServicesUsaRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/markets/': typeof MarketsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/india'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/markets/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/india'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies'
    | '/industries'
    | '/insights'
    | '/markets'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/case-studies/australia-tga'
    | '/case-studies/eu-mdr-remediation'
    | '/case-studies/fda-biocompatibility'
    | '/case-studies/fda-simulated-use'
    | '/case-studies/test-smarter'
    | '/industries/cosmetics'
    | '/industries/ivd'
    | '/industries/medical-devices'
    | '/insights/eu-mdr-2026'
    | '/insights/fda-inspections-2026'
    | '/insights/fda-qmsr-2026'
    | '/services/australia'
    | '/services/brazil'
    | '/services/canada'
    | '/services/eu'
    | '/services/india'
    | '/services/iso-13485'
    | '/services/mdsap'
    | '/services/regulatory-affairs'
    | '/services/uae'
    | '/services/uk'
    | '/services/usa'
    | '/case-studies/'
    | '/industries/'
    | '/insights/'
    | '/markets/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  IndustriesCosmeticsRoute: typeof IndustriesCosmeticsRoute
  IndustriesIvdRoute: typeof IndustriesIvdRoute
  IndustriesMedicalDevicesRoute: typeof IndustriesMedicalDevicesRoute
  InsightsEuMdr2026Route: typeof InsightsEuMdr2026Route
  InsightsFdaInspections2026Route: typeof InsightsFdaInspections2026Route
  InsightsFdaQmsr2026Route: typeof InsightsFdaQmsr2026Route
  ServicesAustraliaRoute: typeof ServicesAustraliaRoute
  ServicesBrazilRoute: typeof ServicesBrazilRoute
  ServicesCanadaRoute: typeof ServicesCanadaRoute
  ServicesEuRoute: typeof ServicesEuRoute
  ServicesIndiaRoute: typeof ServicesIndiaRoute
  ServicesIso13485Route: typeof ServicesIso13485Route
  ServicesMdsapRoute: typeof ServicesMdsapRoute
  ServicesRegulatoryAffairsRoute: typeof ServicesRegulatoryAffairsRoute
  ServicesUaeRoute: typeof ServicesUaeRoute
  ServicesUkRoute: typeof ServicesUkRoute
  ServicesUsaRoute: typeof ServicesUsaRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/australia-tga': {
      id: '/case-studies/australia-tga'
      path: '/australia-tga'
      fullPath: '/case-studies/australia-tga'
      preLoaderRoute: typeof CaseStudiesAustraliaTgaRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/eu-mdr-remediation': {
      id: '/case-studies/eu-mdr-remediation'
      path: '/eu-mdr-remediation'
      fullPath: '/case-studies/eu-mdr-remediation'
      preLoaderRoute: typeof CaseStudiesEuMdrRemediationRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/fda-biocompatibility': {
      id: '/case-studies/fda-biocompatibility'
      path: '/fda-biocompatibility'
      fullPath: '/case-studies/fda-biocompatibility'
      preLoaderRoute: typeof CaseStudiesFdaBiocompatibilityRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/fda-simulated-use': {
      id: '/case-studies/fda-simulated-use'
      path: '/fda-simulated-use'
      fullPath: '/case-studies/fda-simulated-use'
      preLoaderRoute: typeof CaseStudiesFdaSimulatedUseRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/test-smarter': {
      id: '/case-studies/test-smarter'
      path: '/test-smarter'
      fullPath: '/case-studies/test-smarter'
      preLoaderRoute: typeof CaseStudiesTestSmarterRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/cosmetics': {
      id: '/industries/cosmetics'
      path: '/industries/cosmetics'
      fullPath: '/industries/cosmetics'
      preLoaderRoute: typeof IndustriesCosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/ivd': {
      id: '/industries/ivd'
      path: '/industries/ivd'
      fullPath: '/industries/ivd'
      preLoaderRoute: typeof IndustriesIvdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/medical-devices': {
      id: '/industries/medical-devices'
      path: '/industries/medical-devices'
      fullPath: '/industries/medical-devices'
      preLoaderRoute: typeof IndustriesMedicalDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/eu-mdr-2026': {
      id: '/insights/eu-mdr-2026'
      path: '/insights/eu-mdr-2026'
      fullPath: '/insights/eu-mdr-2026'
      preLoaderRoute: typeof InsightsEuMdr2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/fda-inspections-2026': {
      id: '/insights/fda-inspections-2026'
      path: '/insights/fda-inspections-2026'
      fullPath: '/insights/fda-inspections-2026'
      preLoaderRoute: typeof InsightsFdaInspections2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/fda-qmsr-2026': {
      id: '/insights/fda-qmsr-2026'
      path: '/insights/fda-qmsr-2026'
      fullPath: '/insights/fda-qmsr-2026'
      preLoaderRoute: typeof InsightsFdaQmsr2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/australia': {
      id: '/services/australia'
      path: '/services/australia'
      fullPath: '/services/australia'
      preLoaderRoute: typeof ServicesAustraliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brazil': {
      id: '/services/brazil'
      path: '/services/brazil'
      fullPath: '/services/brazil'
      preLoaderRoute: typeof ServicesBrazilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/canada': {
      id: '/services/canada'
      path: '/services/canada'
      fullPath: '/services/canada'
      preLoaderRoute: typeof ServicesCanadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/eu': {
      id: '/services/eu'
      path: '/services/eu'
      fullPath: '/services/eu'
      preLoaderRoute: typeof ServicesEuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/india': {
      id: '/services/india'
      path: '/services/india'
      fullPath: '/services/india'
      preLoaderRoute: typeof ServicesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/iso-13485': {
      id: '/services/iso-13485'
      path: '/services/iso-13485'
      fullPath: '/services/iso-13485'
      preLoaderRoute: typeof ServicesIso13485RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mdsap': {
      id: '/services/mdsap'
      path: '/services/mdsap'
      fullPath: '/services/mdsap'
      preLoaderRoute: typeof ServicesMdsapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/regulatory-affairs': {
      id: '/services/regulatory-affairs'
      path: '/services/regulatory-affairs'
      fullPath: '/services/regulatory-affairs'
      preLoaderRoute: typeof ServicesRegulatoryAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uae': {
      id: '/services/uae'
      path: '/services/uae'
      fullPath: '/services/uae'
      preLoaderRoute: typeof ServicesUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uk': {
      id: '/services/uk'
      path: '/services/uk'
      fullPath: '/services/uk'
      preLoaderRoute: typeof ServicesUkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/usa': {
      id: '/services/usa'
      path: '/services/usa'
      fullPath: '/services/usa'
      preLoaderRoute: typeof ServicesUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesAustraliaTgaRoute: typeof CaseStudiesAustraliaTgaRoute
  CaseStudiesEuMdrRemediationRoute: typeof CaseStudiesEuMdrRemediationRoute
  CaseStudiesFdaBiocompatibilityRoute: typeof CaseStudiesFdaBiocompatibilityRoute
  CaseStudiesFdaSimulatedUseRoute: typeof CaseStudiesFdaSimulatedUseRoute
  CaseStudiesTestSmarterRoute: typeof CaseStudiesTestSmarterRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesAustraliaTgaRoute: CaseStudiesAustraliaTgaRoute,
  CaseStudiesEuMdrRemediationRoute: CaseStudiesEuMdrRemediationRoute,
  CaseStudiesFdaBiocompatibilityRoute: CaseStudiesFdaBiocompatibilityRoute,
  CaseStudiesFdaSimulatedUseRoute: CaseStudiesFdaSimulatedUseRoute,
  CaseStudiesTestSmarterRoute: CaseStudiesTestSmarterRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  IndustriesCosmeticsRoute: IndustriesCosmeticsRoute,
  IndustriesIvdRoute: IndustriesIvdRoute,
  IndustriesMedicalDevicesRoute: IndustriesMedicalDevicesRoute,
  InsightsEuMdr2026Route: InsightsEuMdr2026Route,
  InsightsFdaInspections2026Route: InsightsFdaInspections2026Route,
  InsightsFdaQmsr2026Route: InsightsFdaQmsr2026Route,
  ServicesAustraliaRoute: ServicesAustraliaRoute,
  ServicesBrazilRoute: ServicesBrazilRoute,
  ServicesCanadaRoute: ServicesCanadaRoute,
  ServicesEuRoute: ServicesEuRoute,
  ServicesIndiaRoute: ServicesIndiaRoute,
  ServicesIso13485Route: ServicesIso13485Route,
  ServicesMdsapRoute: ServicesMdsapRoute,
  ServicesRegulatoryAffairsRoute: ServicesRegulatoryAffairsRoute,
  ServicesUaeRoute: ServicesUaeRoute,
  ServicesUkRoute: ServicesUkRoute,
  ServicesUsaRoute: ServicesUsaRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
